# Generated by Django 3.0 on 2020-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateTimeField()),
                ('Comments', models.TextField(max_length=60)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Doctor')),
            ],
        ),
    ]
